# Site settings
title: RG
description: RG
 baseurl: "/RG" # the subpath of your site, e.g. /blog
 url: "https://RG32092.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: RG
user_description: Audio Engineer
user_title: Audio Engineer
email: RandyGarcia32092@gmail.com
twitter_username: @IAMKnowledge
github_username:  RG32092
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
